version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
      nodejs: 10
    commands:
      - npm install -g serverless
  build:
    commands:
      - ./gradlew clean build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
      - sls deploy -v -s $ENV_NAME
